name: Setup Environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      # 🛠️ Step to install TA-Lib from source
      - name: Install TA-Lib from source
        run: |
          sudo apt-get update
          sudo apt-get install -y wget build-essential
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib
          ./configure --prefix=/usr
          make
          sudo make install
          cd ..

      # 🐍 Python dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements.txt found"; fi
          pip install ta-lib

      - name: Verify Python Installation
        run: python --version

      - name: Verify Installed Libraries
        run: pip list
