name: Setup Environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-setup:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      # Step 3: Install system dependencies for TA-Lib
      - name: Install system dependencies for TA-Lib
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libta-lib-dev

      # Step 4: Install Python dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements.txt found"; fi
          pip install ta-lib

      # Step 5: Validate Python Installation
      - name: Verify Python Installation
        run: python --version

      # Step 6: Validate Installed Libraries
      - name: Verify Installed Libraries
        run: pip list
